[tasks.put_install_script]
command = "aws"
args = ["s3", "cp", "./install.sh", "s3://hacoenv.ymgyt.io/install.sh"]

[tasks.put_binary]
command = "aws"
args = ["s3", "cp", "./target/release/hacoenv", "s3://hacoenv.ymgyt.io/dist/x86_64-apple-darwin/hacoenv"]

[tasks.build]
command = "cargo"
args = ["build", "--release"]

[tasks.deploy]
dependencies = [
   "build",
   "put_binary"
]
